language: php
php:
  - '5.4'
before_install:
  - /home/travis/.phpenv/versions/5.4/bin/composer self-update
  - composer install
before_script:
  - composer update
branches:
  only:
    - master
script: phpunit
notifications:
    on_success: never
    on_failure: never